export const INSERT_DATA = "INSERT_DATA";
export const VIEW_DATA = "VIEW_DATA";
export const UPDATE_DATA = "UPDATE_DATA";
export const DELETE_DATA = "DELETE_DATA";

export const INSERT_CATEGORY_DATA = "INSERT_CATEGORY_DATA";
export const VIEW_CATEGORY_DATA = "VIEW_CATEGORY_DATA";

export const INSERT_PRODUCT_DATA = "INSERT_PRODUCT_DATA";
export const VIEW_PRODUCT_DATA = "VIEW_PRODUCT_DATA";
